const ExcelSchema = [
  "ID",
  "Name",
  "Symbol",
  "Market Pairs",
  "Date Added",
  "Tags",
  "Max Supply",
  "Circulating Supply",
  "Total Supply",
  "Percentage In Circulation",
  "Market Cap",
  "Fully Diluted Market Cap",
  //   "Platform ID",
  //   "Platform Name",
  //   "Platform Symbol",
  //   "Platform Token Address",
  //   "Rank",
  //   "Reported Circulating Supply",
  //   "Reported Market Cap",
  //   "Last Updated",
  //   "Price",
  //   "Volume 24H",
  //   "Volume Change 24H",
  //   "% Change 1H",
  //   "% Change 24H",
  //   "% Change 7D",
  //   "% Change 30D",
  //   "% Change 60D",
  //   "% Change 90D",
  //   "Market Cap",
  //   "Market Cap Dominance",
  //   "Fully Diluted Market Cap",
  //   "TVL",
];

module.exports = {
  ExcelSchema,
};
